// Source.cpp Hiromi Kageyama
// Write a c++ program that uses the trunc function in FLTK

// generated by Fast Light User Interface Designer (fluid) version 1.0305
// This program does not work yet

#include "TestOne.h"
#include <stdio.h>
#include <stdlib.h>
#include <iostream>

Fl_Input* test_input = (Fl_Input*)0;
Fl_Output* test_output = (Fl_Output*)0;

int main(int argc, char** argv) {

    Fl_Double_Window* w;

    { Fl_Double_Window* o = new Fl_Double_Window(300, 150);
    w = o; if (w) {/* empty */ }

    o->end();
    } // Fl_Double_Window* o

    w->show(argc, argv);
    return Fl::run();
}
